/* Word lists for the readability engine. Plain data, no logic.
   Loaded in the browser as TDW.Data and in Node via require(). */
(function (root, data) {
  if (typeof module === 'object' && module.exports) module.exports = data;
  else { root.TDW = root.TDW || {}; root.TDW.Data = data; }
})(typeof self !== 'undefined' ? self : this, {

  /* A period after one of these never ends a sentence (lowercase, no final period). */
  ABBREVIATIONS: [
    'mr', 'mrs', 'ms', 'mx', 'dr', 'prof', 'sr', 'jr', 'st', 'mt', 'rev', 'gen', 'col',
    'lt', 'sgt', 'capt', 'gov', 'sen', 'rep', 'fig', 'vs', 'e.g', 'i.e', 'cf', 'approx',
    'dept', 'est', 'vol', 'ph.d', 'feb', 'apr', 'jun', 'jul', 'aug', 'sep', 'sept', 'oct',
    'nov', 'dec'
  ],

  /* Words ending in -ly that are not adverbs, or too common to flag. */
  ADVERB_EXCEPTIONS: [
    'ally', 'anomaly', 'apply', 'assembly', 'beastly', 'belly', 'beverly', 'billy', 'bodily',
    'brotherly', 'bubbly', 'bully', 'burly', 'butterfly', 'chilly', 'comely', 'comply',
    'costly', 'courtly', 'cowardly', 'curly', 'daily', 'dally', 'deadly', 'disorderly',
    'doily', 'dragonfly', 'early', 'earthly', 'easterly', 'elderly', 'ely', 'emily', 'family',
    'fatherly', 'filly', 'firefly', 'fly', 'folly', 'friendly', 'gangly', 'ghostly', 'gnarly',
    'godly', 'grisly', 'grizzly', 'gully', 'heavenly', 'hillbilly', 'hilly', 'holly', 'holy',
    'homely', 'homily', 'hourly', 'imply', 'italy', 'jelly', 'jolly', 'july', 'kelly',
    'kimberly', 'kindly', 'leisurely', 'likely', 'lily', 'lively', 'lonely', 'lovely',
    'lowly', 'manly', 'measly', 'miserly', 'molly', 'monopoly', 'monthly', 'motherly',
    'multiply', 'neighborly', 'nightly', 'northerly', 'oily', 'only', 'orderly', 'panoply',
    'pearly', 'polly', 'potbelly', 'prickly', 'quarterly', 'rally', 'reapply', 'rely', 'reply',
    'resupply', 'sally', 'scholarly', 'seemly', 'shapely', 'shelly', 'sickly', 'silly',
    'sisterly', 'sly', 'smelly', 'southerly', 'sprightly', 'stately', 'supply', 'surly',
    'tally', 'timely', 'ugly', 'underbelly', 'ungodly', 'unfriendly', 'unlikely', 'unruly',
    'unseemly', 'untimely', 'weekly', 'westerly', 'wily', 'wobbly', 'womanly', 'woolly',
    'worldly', 'wrinkly', 'yearly'
  ],

  /* Forms of "to be" that can start a passive phrase (apostrophes normalized to '). */
  BE_FORMS: [
    'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
    "isn't", "aren't", "wasn't", "weren't", "ain't"
  ],

  /* Up to two of these (or any word ending in -ly) may sit between the be-form
     and the participle: "was also often praised", "is being built". */
  PASSIVE_SKIP: [
    'not', 'never', 'also', 'just', 'often', 'always', 'still', 'already', 'then', 'all',
    'being', 'now', 'ever', 'even', 'sometimes', 'well', 'so', 'too', 'very', 'quite',
    'much', 'further', 'soon', 'once'
  ],

  /* Past participles that don't end in -ed. Ambiguous ones (cut, put, set, read, run,
     come, become, cost, hit, hurt, let, shut, spread, split, quit, burst, upset) are left out. */
  IRREGULAR_PARTICIPLES: [
    'arisen', 'awoken', 'beaten', 'begun', 'bent', 'bitten', 'bled', 'blown', 'borne',
    'bought', 'bred', 'broken', 'brought', 'built', 'burnt', 'caught', 'chosen', 'clung',
    'crept', 'dealt', 'drawn', 'dreamt', 'driven', 'drunk', 'dug', 'eaten', 'fallen', 'fed',
    'felt', 'fought', 'found', 'fled', 'flung', 'flown', 'forbidden', 'forgotten', 'forgiven',
    'forsaken', 'frozen', 'given', 'gotten', 'ground', 'grown', 'hung', 'heard', 'hidden',
    'held', 'kept', 'knelt', 'known', 'laid', 'led', 'leapt', 'learnt', 'left', 'lent', 'lit',
    'made', 'meant', 'met', 'mistaken', 'overcome', 'overheard', 'overseen', 'overtaken',
    'overthrown', 'paid', 'proven', 'rebuilt', 'rewritten', 'rid', 'ridden', 'rung', 'risen',
    'said', 'seen', 'sought', 'sold', 'sent', 'sewn', 'shaken', 'shorn', 'shone', 'shot',
    'shown', 'shrunk', 'sung', 'sunk', 'slain', 'slept', 'slid', 'slung', 'smelt', 'sown',
    'spoken', 'sped', 'spent', 'spilt', 'spun', 'sprung', 'stolen', 'stung', 'struck',
    'strung', 'sworn', 'swept', 'swollen', 'swum', 'swung', 'taken', 'taught', 'torn', 'told',
    'thought', 'thrown', 'trodden', 'understood', 'undertaken', 'undone', 'upheld',
    'withdrawn', 'withheld', 'withstood', 'woken', 'won', 'worn', 'woven', 'wept', 'wound',
    'written'
  ],

  /* Words ending in -ed that are not past participles. */
  ED_NOT_PARTICIPLE: [
    'bed', 'beloved', 'breed', 'creed', 'crooked', 'deed', 'embed', 'exceed', 'feed', 'greed',
    'hatred', 'heed', 'hundred', 'indeed', 'infrared', 'jagged', 'kindred', 'naked', 'need',
    'proceed', 'ragged', 'red', 'reed', 'rugged', 'sacred', 'seed', 'shed', 'shred', 'sled',
    'speed', 'steed', 'succeed', 'tweed', 'wed', 'weed', 'wicked'
  ],

  /* Participles that usually describe a state ("I am tired"), so a be-form before
     them is not flagged as passive voice. */
  ADJECTIVAL_PARTICIPLES: [
    'tired', 'interested', 'excited', 'bored', 'married', 'divorced', 'worried', 'scared',
    'frightened', 'pleased', 'surprised', 'satisfied', 'supposed', 'embarrassed', 'confused',
    'frustrated', 'disappointed', 'amazed', 'annoyed', 'relaxed', 'stressed', 'overwhelmed',
    'thrilled', 'delighted', 'exhausted', 'obsessed', 'convinced', 'ashamed', 'engaged',
    'dedicated', 'talented', 'skilled', 'advanced', 'detailed', 'complicated',
    'sophisticated', 'experienced', 'balanced', 'crowded', 'unexpected', 'aged', 'learned',
    'concerned', 'determined', 'involved', 'committed', 'qualified', 'limited', 'prepared',
    'done', 'gone', 'finished', 'born', 'lost', 'based', 'located', 'related', 'connected',
    'closed', 'armed', 'blessed', 'stuck', 'bound'
  ],

  /* Hedges and filler that weaken a sentence. Lowercase; ' matches ' and ’. */
  QUALIFIERS: [
    'i think', 'i believe', 'i feel', 'i guess', 'i suppose', 'i hope to', 'i might',
    'i will try', "i'll try", 'i was wondering', 'i wonder', "i don't think",
    "i don't believe", 'i do not think', 'in my opinion', 'we think', 'we believe',
    'we feel', 'we hope to', 'we might', 'we will try', 'we were wondering', "we don't think",
    'kind of', 'sort of', 'a bit', 'a little bit', 'very', 'really', 'quite', 'somewhat',
    'pretty much', 'just', 'basically', 'actually', 'literally', 'totally', 'maybe',
    'perhaps', 'possibly', 'probably', 'arguably', 'it seems', 'seems to', 'to be honest',
    'honestly', 'in a sense', 'more or less'
  ],

  /* Words that prop up the word after them ("very tired"). */
  INTENSIFIERS: [
    'very', 'really', 'so', 'extremely', 'super', 'incredibly', 'terribly', 'awfully', 'totally',
    'absolutely', 'highly', 'truly', 'deeply', 'utterly', 'exceptionally', 'remarkably', 'quite',
    'pretty'
  ],

  /* One strong word instead of intensifier + adjective: "very tired" -> "exhausted".
     adjective -> comma-separated alternatives, best first. */
  STRONGER: {
    afraid: 'terrified, petrified', angry: 'furious, livid', annoying: 'infuriating, exasperating',
    bad: 'awful, terrible, dreadful', beautiful: 'stunning, gorgeous', big: 'huge, enormous, massive',
    boring: 'tedious, dull', bright: 'brilliant, dazzling', busy: 'swamped, slammed',
    calm: 'serene, tranquil', careful: 'meticulous, cautious', clean: 'spotless, immaculate',
    clear: 'obvious, crystal-clear', clever: 'brilliant, ingenious', close: 'intimate, near',
    cold: 'freezing, frigid', colorful: 'vibrant, vivid', common: 'widespread, ubiquitous',
    competitive: 'cutthroat, ruthless', confused: 'baffled, bewildered', crowded: 'packed, jammed',
    cute: 'adorable, charming', damaged: 'wrecked, ruined', dark: 'pitch-black, murky',
    dear: 'cherished, precious', deep: 'profound, bottomless', different: 'distinct, unlike',
    difficult: 'grueling, arduous, tough', dirty: 'filthy, squalid', dry: 'parched, arid',
    dull: 'tedious, drab', eager: 'keen, avid', easy: 'effortless, simple', effective: 'potent, powerful',
    empty: 'vacant, hollow', excited: 'thrilled, eager', expensive: 'costly, pricey', fast: 'rapid, swift',
    fat: 'obese, plump', frightened: 'terrified, petrified', full: 'packed, stuffed',
    funny: 'hilarious, hysterical', glad: 'delighted, thrilled', good: 'great, excellent, superb',
    great: 'terrific, outstanding', happy: 'thrilled, elated, overjoyed', hard: 'difficult, grueling',
    harsh: 'brutal, cruel', heavy: 'hefty, leaden', helpful: 'invaluable, indispensable',
    high: 'towering, lofty', hot: 'scorching, sweltering', huge: 'colossal, massive',
    hungry: 'starving, ravenous', hurt: 'devastated, wounded', important: 'crucial, vital, essential',
    impressive: 'remarkable, stunning', intelligent: 'brilliant, gifted', interesting: 'fascinating, captivating',
    large: 'huge, vast', lazy: 'idle, sluggish', little: 'tiny, minuscule', long: 'lengthy, endless',
    loud: 'deafening, thunderous', lovely: 'delightful, exquisite', mad: 'furious, livid',
    many: 'countless, numerous', mean: 'cruel, vicious', messy: 'chaotic, sloppy',
    necessary: 'essential, vital', nervous: 'anxious, jittery', new: 'brand-new, novel',
    nice: 'kind, lovely, pleasant', noisy: 'raucous, deafening', obvious: 'glaring, blatant',
    old: 'ancient, aged', painful: 'agonizing, excruciating', pale: 'ashen, pallid',
    perfect: 'flawless, impeccable', polite: 'gracious, courteous', poor: 'destitute, penniless',
    popular: 'beloved, sought-after', powerful: 'mighty, potent', pretty: 'beautiful, gorgeous',
    proud: 'triumphant, elated', quick: 'rapid, swift', quiet: 'silent, hushed', rare: 'scarce, unusual',
    rich: 'wealthy, affluent', rough: 'coarse, rugged', rude: 'insolent, vulgar', sad: 'miserable, heartbroken',
    safe: 'secure, protected', scared: 'terrified, petrified', scary: 'terrifying, chilling',
    serious: 'grave, solemn', sharp: 'keen, razor-sharp', short: 'brief, tiny', shy: 'timid, bashful',
    similar: 'alike, identical', simple: 'basic, plain', skinny: 'gaunt, bony', slow: 'sluggish, crawling',
    small: 'tiny, minuscule', smart: 'brilliant, sharp', smooth: 'sleek, silky', soft: 'plush, velvety',
    sorry: 'apologetic, remorseful', special: 'exceptional, unique', strange: 'bizarre, odd',
    strong: 'powerful, mighty', stupid: 'idiotic, senseless', successful: 'thriving, prosperous',
    sure: 'certain, positive', surprised: 'stunned, astonished', sweet: 'charming, lovely',
    tall: 'towering, lofty', tasty: 'delicious, delectable', thin: 'slender, gaunt', thirsty: 'parched',
    tight: 'snug, taut', tired: 'exhausted, drained, weary', ugly: 'hideous, grotesque',
    unhappy: 'miserable, wretched', unusual: 'extraordinary, remarkable', upset: 'distraught, devastated',
    useful: 'invaluable, indispensable', valuable: 'precious, priceless', warm: 'balmy, toasty',
    weak: 'frail, feeble', weird: 'bizarre, strange', wet: 'soaked, drenched', wide: 'vast, sweeping',
    wise: 'sage, insightful', worried: 'anxious, distressed', wrong: 'mistaken, incorrect'
  },

  /* Wordy words and phrases with plainer options.
     [variants separated by |, suggestion]. Suggestion is a comma-separated list of
     alternatives; an empty string means "cut it". ' matches ' and ’. */
  COMPLEX: [
    ['a number of', 'some, many'],
    ['a large number of', 'many'],
    ['a small number of', 'a few'],
    ['a majority of|the majority of', 'most'],
    ['absolutely essential', 'essential'],
    ['accompany|accompanies|accompanied|accompanying', 'go with'],
    ['accomplish|accomplishes|accomplished|accomplishing', 'do, finish'],
    ['accordingly', 'so'],
    ['accrue|accrues|accrued|accruing', 'build up'],
    ['actionable', 'practical, useful'],
    ['additional', 'more, extra'],
    ['adjacent to', 'next to'],
    ['advantageous', 'helpful'],
    ['adversely impact|adversely impacts|adversely impacted|adversely affect|adversely affects|adversely affected', 'hurt'],
    ['aforementioned', 'this, these'],
    ['aggregate', 'total'],
    ['alleviate|alleviates|alleviated|alleviating', 'ease, reduce'],
    ['along the lines of', 'like'],
    ['already existing', 'existing'],
    ['alternatively', 'or'],
    ['ameliorate|ameliorates|ameliorated|ameliorating', 'improve'],
    ['anticipate|anticipates|anticipated|anticipating', 'expect'],
    ['apparent', 'clear'],
    ['approximately', 'about'],
    ['as a means of', 'to'],
    ['as of yet|as yet', 'yet'],
    ['as to', 'about'],
    ['ascertain|ascertains|ascertained|ascertaining', 'find out'],
    ['assist|assists|assisted|assisting|assistance', 'help'],
    ['at all times', 'always'],
    ['at the end of the day', 'in the end'],
    ['at the present time|at this point in time|at this moment in time|at this time', 'now'],
    ['attain|attains|attained|attaining', 'reach'],
    ['attempt|attempts|attempted|attempting', 'try'],
    ['bandwidth', 'time'],
    ['basic fundamentals', 'basics'],
    ['be advised that|be advised', ''],
    ['best-in-class|world-class', 'best'],
    ['by means of', 'by, with'],
    ['capability|capabilities', 'ability'],
    ['caveat', 'warning'],
    ['circle back', 'follow up'],
    ['in close proximity to|close proximity', 'near'],
    ['come to a conclusion|came to a conclusion', 'conclude'],
    ['commence|commences|commenced|commencing', 'start'],
    ['completely eliminate|completely eliminated', 'cut'],
    ['comply with|complied with', 'follow'],
    ['component|components', 'part'],
    ['comprise|comprises|comprised|comprising', 'include, make up'],
    ['concerning', 'about'],
    ['conduct an investigation', 'investigate'],
    ['consequently', 'so'],
    ['consolidate|consolidates|consolidated|consolidating', 'combine'],
    ['constitute|constitutes|constituted', 'make up'],
    ['cutting-edge', 'new, latest'],
    ['deem|deems|deemed', 'think'],
    ['deep dive', 'close look'],
    ['delve into|delves into|delved into|delving into', 'look at, explore'],
    ['demonstrate|demonstrates|demonstrated|demonstrating', 'show'],
    ['depart|departs|departed|departing', 'leave'],
    ['despite the fact that|in spite of the fact that', 'although'],
    ['disseminate|disseminates|disseminated|disseminating', 'share, send'],
    ['due to the fact that|owing to the fact that|on the grounds that|for the reason that', 'because'],
    ['during the course of|during the period of', 'during'],
    ['each and every', 'each, every'],
    ['effectuate|effectuates|effectuated', 'cause, carry out'],
    ['eliminate|eliminates|eliminated|eliminating', 'cut, remove'],
    ['embark on|embarks on|embarked on|embarking on', 'start'],
    ['empower|empowers|empowered|empowering', 'help, let'],
    ['encounter|encounters|encountered|encountering', 'meet, face'],
    ['end result', 'result'],
    ['endeavor|endeavors|endeavored|endeavoring|endeavour|endeavours', 'try'],
    ['ensure|ensures|ensured|ensuring', 'make sure'],
    ['enumerate|enumerates|enumerated', 'list'],
    ['equitable', 'fair'],
    ['evident', 'clear'],
    ['exhibit|exhibits|exhibited|exhibiting', 'show'],
    ['expedite|expedites|expedited|expediting', 'speed up'],
    ['expenditure|expenditures', 'spending, cost'],
    ['facilitate|facilitates|facilitated|facilitating', 'help, ease'],
    ['feasible', 'doable'],
    ['final outcome', 'outcome'],
    ['finalize|finalizes|finalized|finalizing', 'finish'],
    ['first and foremost', 'first'],
    ['for a period of', 'for'],
    ['for the purpose of', 'to, for'],
    ['forfeit|forfeits|forfeited', 'lose, give up'],
    ['foster|fosters|fostered|fostering', 'build, grow'],
    ['free gift', 'gift'],
    ['frequently', 'often'],
    ['future plans', 'plans'],
    ['game-changer|game changer|game-changing', 'big change'],
    ['give consideration to', 'consider'],
    ['going forward|moving forward', 'from now on'],
    ['has the ability to|have the ability to|has the capacity to|have the capacity to', 'can'],
    ['holistic', 'whole, complete'],
    ['however', 'but'],
    ['ideate|ideates|ideating', 'brainstorm'],
    ['identical', 'same'],
    ['immediately', 'now, at once'],
    ['impactful', 'strong'],
    ['in a timely manner', 'on time, quickly'],
    ['in accordance with', 'under, by'],
    ['in addition to', 'besides'],
    ['in addition', 'also'],
    ['in an effort to', 'to'],
    ['in lieu of', 'instead of'],
    ['in order that', 'so'],
    ['in order to', 'to'],
    ['in regard to|in regards to|with regard to|with respect to|in reference to|with reference to|in relation to', 'about'],
    ['in the amount of', 'for'],
    ['in the event that|in the event of', 'if'],
    ['in the near future|at an early date', 'soon'],
    ['in the process of', ''],
    ["in this day and age|in today's world|in today's fast-paced world", 'today'],
    ['in view of the fact that|inasmuch as', 'since'],
    ['inception', 'start'],
    ['incumbent upon', 'must'],
    ['indicate|indicates|indicated|indicating', 'show'],
    ['indication', 'sign'],
    ['initial', 'first'],
    ['initiate|initiates|initiated|initiating', 'start'],
    ['is able to|are able to|was able to|were able to', 'can, could'],
    ['is applicable to', 'applies to'],
    ['is in need of|are in need of', 'needs'],
    ['is indicative of', 'shows'],
    ['is responsible for', 'handles'],
    ['it goes without saying that|it goes without saying|needless to say', ''],
    ['it is essential that', 'must'],
    ["it is important to note that|it should be noted that|it is worth noting that|it's worth noting that|it is worth mentioning that", ''],
    ['learnings', 'lessons'],
    ['leverage|leverages|leveraged|leveraging', 'use'],
    ['low-hanging fruit', 'easy wins'],
    ['magnitude', 'size'],
    ['make a decision|made a decision|makes a decision', 'decide'],
    ['make an assumption|made an assumption', 'assume'],
    ['make an effort|made an effort', 'try'],
    ['methodology', 'method'],
    ['minimize|minimizes|minimized|minimizing', 'cut, reduce'],
    ['modify|modifies|modified|modifying', 'change'],
    ['move the needle', 'matter'],
    ['necessitate|necessitates|necessitated', 'need'],
    ['notify|notifies|notified|notifying', 'tell'],
    ['notwithstanding', 'despite, still'],
    ['numerous', 'many'],
    ['objective|objectives', 'goal'],
    ['obtain|obtains|obtained|obtaining', 'get'],
    ['on a daily basis', 'daily'],
    ['on a monthly basis', 'monthly'],
    ['on a regular basis', 'regularly'],
    ['on a weekly basis', 'weekly'],
    ['optimal|optimum', 'best'],
    ['optimize|optimizes|optimized|optimizing', 'improve'],
    ['paradigm shift', 'big change'],
    ['participate|participates|participated|participating', 'take part, join'],
    ['past history', 'history'],
    ['per annum', 'a year'],
    ['perform|performs', 'do'],
    ['pertaining to', 'about'],
    ['possess|possesses|possessed', 'have, own'],
    ['preclude|precludes|precluded', 'prevent'],
    ['previously', 'before'],
    ['prior to', 'before'],
    ['prioritize|prioritizes|prioritized|prioritizing', 'focus on'],
    ['procure|procures|procured|procuring', 'get, buy'],
    ['proficiency', 'skill'],
    ['provide assistance', 'help'],
    ['provided that', 'if'],
    ['purchase|purchases|purchased|purchasing', 'buy'],
    ['pursuant to', 'under'],
    ['reach out to|reached out to|reaching out to|reaches out to', 'contact'],
    ['regarding', 'about'],
    ['relocate|relocates|relocated|relocating', 'move'],
    ['remainder', 'rest'],
    ['remuneration', 'pay'],
    ['reside|resides|resided|residing', 'live'],
    ['retain|retains|retained|retaining', 'keep'],
    ['robust', 'strong'],
    ['seamless|seamlessly', 'smooth'],
    ['selection', 'choice'],
    ['similar to', 'like'],
    ['solicit|solicits|solicited|soliciting', 'ask for'],
    ['state-of-the-art', 'latest'],
    ['streamline|streamlines|streamlined|streamlining', 'simplify'],
    ['subsequent', 'later, next'],
    ['subsequently', 'later, then'],
    ['substantial', 'large, big'],
    ['sufficient', 'enough'],
    ['synergy|synergies', 'teamwork'],
    ['take into consideration|takes into consideration|took into consideration', 'consider'],
    ['terminate|terminates|terminated|terminating', 'end, stop'],
    ['the fact that', 'that'],
    ['thought leader|thought leaders|thought leadership', 'expert'],
    ['touch base', 'talk'],
    ['transmit|transmits|transmitted|transmitting', 'send'],
    ['unexpected surprise', 'surprise'],
    ['until such time as', 'until'],
    ['utilize|utilizes|utilized|utilizing|utilization', 'use'],
    ['utmost', 'most'],
    ['validate|validates|validated|validating', 'confirm'],
    ['value-add', 'benefit'],
    ['very unique|totally unique', 'unique'],
    ['viable', 'workable'],
    ['whereas', 'while'],
    ['whether or not', 'whether'],
    ['with the exception of', 'except']
  ]
});
